# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = demo
DESTDIR = ./x64/Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
HEADERS += ./demo.h \
    ./threadpool.h
SOURCES += ./demo.cpp \
    ./main.cpp
FORMS += ./demo.ui
RESOURCES += demo.qrc
